spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/api_utilisateur
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: api-utilisateur
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
# Ce sont les parametres de sécurité
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://keycloackdev.afrilins.net/auth/realms/springBootkeycloak/protocol/openid-connect/token
        #            token-uri: https://keycloackdev.afrilins.net/auth/realms/secuGlobal/protocol/openid-connect/token
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-secret: c16893e3-e087-4917-aec2-bb621ea86f67
            client-id: my_client

# C'es la configuration minimal d'un client qui veut accéder à un serveur de découverte
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

server:
  port: 8083 # C'est le numéro de port que cet microservice va tourner

#ceci concerne la configuration minimale pour mon keyclok
keycloak:
  realm: springBootkeycloak # C'est le nom de mon domaine
  auth-server-url:  https://keycloackdev.afrilins.net/auth
    #  auth-server-url: https://keycloackdev.afrilins.net/auth
  ssl-required: external
  resource: my_client # c'est mon id client dans keycloak
  bearer-only: true # permet d'avoir accès au token
  credentials:
    secret: c16893e3-e087-4917-aec2-bb621ea86f67  # Vue que mon client à été défini comme confidentiel alors cela nécessite son mot de passe
