#configuration database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/compte_utilisateur
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # nom de l'application
  application:
    name: api-compte
#configuration client eureka
eureka:

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
#port de l'api
server:
  port: 8808
