#configuration database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/compte_utilisateur
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # nom de l'application
  application:
    name: api-compte
  # Ce sont les parametres de sécurité
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: https://keycloackdev.afrilins.net/auth/realms/springBootkeycloak/protocol/openid-connect/token
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-secret: 4cee3515-2c12-42e5-8d9c-1e4d595774f3
            client-id: my_hotel
#configuration client eureka
eureka:

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
#port de l'api
server:
  port: 8808


#ceci concerne la configuration minimale pour mon keyclok
keycloak:
  realm: springBootkeycloak # C'est le nom de mon domaine
  auth-server-url:  https://keycloackdev.afrilins.net/auth
  #  auth-server-url: https://keycloackdev.afrilins.net/auth
  ssl-required: external
  resource: my_hotel # c'est mon id client dans keycloak
  bearer-only: true # permet d'avoir accès au token
  credentials:
    secret: 4cee3515-2c12-42e5-8d9c-1e4d595774f3 # Vue que mon client à été défini comme confidentiel alors cela nécessite son mot de passe
